# **PROJECT TITLE :**

![Stress](Images/Stress.png)

In [1]:
# Importing Libraries
import os
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

# **1. EXPLORATORY DATA ANALYSIS**

In [2]:
# Loading the dataset
df_15sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_15sn.csv")
df_15sn

       Subject   eda     bvp   temp   x   y   z  emotion
0            1  0.00   -0.03  31.63 -13 -18  62        0
1            1  0.04    5.06  31.63 -15 -18  62        0
2            1  0.08   17.91  31.63 -14 -17  62        0
3            1  0.08   79.34  31.63 -16 -17  60        0
4            1  0.08  228.25  31.63   3 -12  63        0
...        ...   ...     ...    ...  ..  ..  ..      ...
39195       20  0.39  144.78  36.21 -64  -1  -9        1
39196       20  0.39  -63.51  36.18 -69   3  -8        1
39197       20  0.39 -289.96  36.18 -66   6   9        1
39198       20  0.39  -67.96  36.18 -66   5   5        1
39199       20  0.39   20.06  36.18 -64   5 -16        1

[39200 rows x 8 columns]

In [3]:
# Displaying the shape of the DataFrame
df_15sn.shape

(39200, 8)

In [4]:
# Get an overview of the df_15sn DataFrame
df_15sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39200 entries, 0 to 39199
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  39200 non-null  int64
 1   eda      39200 non-null  float64
 2   bvp      39200 non-null  float64
 3   temp     39200 non-null  float64
 4   x        39200 non-null  int64
 5   y        39200 non-null  int64
 6   z        39200 non-null  int64
 7   emotion  39200 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 2.4 MB

In [5]:
# checking missing values in df_15sn
df_15sn.isnull().sum()

Subject    0
eda        0
bvp        0
temp       0
x          0
y          0
z          0
emotion    0
dtype: int64

There are no missing values in df_15sn

In [6]:
# checking for duplicates
df_15sn.duplicated().sum()

281

There are 281 duplicates in df_15sn.

In [7]:
# Removing duplicates if any
df_15sn.drop_duplicates(inplace=True)

In [8]:
# Check number of rows before
before = df_15sn.shape[0]

# Drop duplicates
df_15 = df_15sn.drop_duplicates()

# Check number of rows after
after = df_15sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 38919
Rows after: 38919
Duplicates removed: 0

In [9]:
# Check for remaining duplicates
duplicates_exist = df_15.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

All duplicates have been removed.

In [10]:
# Load the 30-second signals data
df_30sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_30sn.csv")
df_30sn

       subjet   eda     bvp   temp   x   y   z  emotion
0           1  0.00   -0.03  31.63 -13 -18  62        0
1           1  0.04    5.06  31.63 -15 -18  62        0
2           1  0.08   17.91  31.63 -14 -17  62        0
3           1  0.08   79.34  31.63 -16 -17  60        0
4           1  0.08  228.25  31.63   3 -12  63        0
...       ...   ...     ...    ...  ..  ..  ..      ...
82595      20  0.37   12.99  36.13 -63  -4 -23        1
82596      20  0.32   78.13  36.13 -59 -14 -34        1
82597      20  0.30  352.78  36.13 -58  -8  -9        1
82598      20  0.37  -74.11  36.13 -64  -9 -17        1
82599      20  0.38 -181.62  36.13 -62  -4 -11        1

[82600 rows x 8 columns]

In [11]:
# Checking the shape of the df_30sn DataFrame
df_30sn.shape

(82600, 8)

In [12]:
# Get an overview of the df_30sn DataFrame
df_30sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82600 entries, 0 to 82599
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subjet   82600 non-null  int64
 1   eda      82600 non-null  float64
 2   bvp      82600 non-null  float64
 3   temp     82600 non-null  float64
 4   x        82600 non-null  int64
 5   y        82600 non-null  int64
 6   z        82600 non-null  int64
 7   emotion  82600 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 5.0 MB

In [13]:
# checking for missing values in df_30sn
df_30sn.isnull().sum()

subjet     0
eda        0
bvp        0
temp       0
x          0
y          0
z          0
emotion    0
dtype: int64

In [14]:
# checking for duplicates in df_30sn
df_30sn.duplicated().sum()

594

There are 594 duplicates.

In [15]:
# Check number of rows before
before = df_30sn.shape[0]

# Drop duplicates
df_15 = df_30sn.drop_duplicates()

# Check number of rows after
after = df_30sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 82600
Rows after: 82600
Duplicates removed: 0

In [16]:
# Check for remaining duplicates
duplicates_exist = df_30sn.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

There are still duplicates.

In [17]:
# Load the 60-second signals data
df_60sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_60sn.csv")
df_60sn

        Subject   eda     bvp   temp   x   y   z  emotion
0             1  0.00   -0.03  31.63 -13 -18  62        0
1             1  0.04    5.06  31.63 -15 -18  62        0
2             1  0.08   17.91  31.63 -14 -17  62        0
3             1  0.08   79.34  31.63 -16 -17  60        0
4             1  0.08  228.25  31.63   3 -12  63        0
...         ...   ...     ...    ...  ..  ..  ..      ...
167995       20  0.33  -35.69  36.05 -53  23  16        1
167996       20  0.35  291.37  36.11 -66  23   1        1
167997       20  0.35  -99.97  36.11 -63  19  -8        1
167998       20  0.35  -48.63  36.11 -61  22 -10        1
167999       20  0.34   59.01  36.11 -61  20 -10        1

[168000 rows x 8 columns]

In [18]:
# Check number of rows before
before = df_60sn.shape[0]

# Drop duplicates
df_15 = df_60sn.drop_duplicates()

# Check number of rows after
after = df_60sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 168000
Rows after: 168000
Duplicates removed: 0

In [19]:
# Check for remaining duplicates
duplicates_exist = df_60sn.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

There are still duplicates.