# **PROJECT TITLE :EMOTION CLASSIFICATION FROM BIOSENSOR DATA**

![Stress](Images/Stress.png)

In [1]:
# Importing Libraries
import os
import pandas as pd
import numpy as np  
import matplotlib.pyplot as plt 
import seaborn as sns

# **1. DATA LOADING AND EXPLORATION**

### **i.) Loading the Physiological Signals Data**

In [2]:
# Loading the dataset
df_15sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_15sn.csv")
df_15sn

       Subject   eda     bvp   temp   x   y   z  emotion
0            1  0.00   -0.03  31.63 -13 -18  62        0
1            1  0.04    5.06  31.63 -15 -18  62        0
2            1  0.08   17.91  31.63 -14 -17  62        0
3            1  0.08   79.34  31.63 -16 -17  60        0
4            1  0.08  228.25  31.63   3 -12  63        0
...        ...   ...     ...    ...  ..  ..  ..      ...
39195       20  0.39  144.78  36.21 -64  -1  -9        1
39196       20  0.39  -63.51  36.18 -69   3  -8        1
39197       20  0.39 -289.96  36.18 -66   6   9        1
39198       20  0.39  -67.96  36.18 -66   5   5        1
39199       20  0.39   20.06  36.18 -64   5 -16        1

[39200 rows x 8 columns]

In [3]:
# Displaying the shape of the DataFrame
df_15sn.shape

(39200, 8)

In [4]:
# Get an overview of the df_15sn DataFrame
df_15sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39200 entries, 0 to 39199
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  39200 non-null  int64
 1   eda      39200 non-null  float64
 2   bvp      39200 non-null  float64
 3   temp     39200 non-null  float64
 4   x        39200 non-null  int64
 5   y        39200 non-null  int64
 6   z        39200 non-null  int64
 7   emotion  39200 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 2.4 MB

In [5]:
# checking missing values in df_15sn
df_15sn.isnull().sum()

Subject    0
eda        0
bvp        0
temp       0
x          0
y          0
z          0
emotion    0
dtype: int64

There are no missing values in df_15sn

In [6]:
# checking for duplicates
df_15sn.duplicated().sum()

281

There are 281 duplicates in df_15sn.

In [7]:
# Removing duplicates if any
df_15sn.drop_duplicates(inplace=True)

In [8]:
# Check number of rows before
before = df_15sn.shape[0]

# Drop duplicates
df_15 = df_15sn.drop_duplicates()

# Check number of rows after
after = df_15sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 38919
Rows after: 38919
Duplicates removed: 0

In [9]:
# Check for remaining duplicates
duplicates_exist = df_15.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

All duplicates have been removed.

In [10]:
# Load the 30-second signals data
df_30sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_30sn.csv")
df_30sn

       subjet   eda     bvp   temp   x   y   z  emotion
0           1  0.00   -0.03  31.63 -13 -18  62        0
1           1  0.04    5.06  31.63 -15 -18  62        0
2           1  0.08   17.91  31.63 -14 -17  62        0
3           1  0.08   79.34  31.63 -16 -17  60        0
4           1  0.08  228.25  31.63   3 -12  63        0
...       ...   ...     ...    ...  ..  ..  ..      ...
82595      20  0.37   12.99  36.13 -63  -4 -23        1
82596      20  0.32   78.13  36.13 -59 -14 -34        1
82597      20  0.30  352.78  36.13 -58  -8  -9        1
82598      20  0.37  -74.11  36.13 -64  -9 -17        1
82599      20  0.38 -181.62  36.13 -62  -4 -11        1

[82600 rows x 8 columns]

In [11]:
# Checking the shape of the df_30sn DataFrame
df_30sn.shape

(82600, 8)

In [12]:
# Get an overview of the df_30sn DataFrame
df_30sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82600 entries, 0 to 82599
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subjet   82600 non-null  int64
 1   eda      82600 non-null  float64
 2   bvp      82600 non-null  float64
 3   temp     82600 non-null  float64
 4   x        82600 non-null  int64
 5   y        82600 non-null  int64
 6   z        82600 non-null  int64
 7   emotion  82600 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 5.0 MB

In [13]:
# checking for missing values in df_30sn
df_30sn.isnull().sum()

subjet     0
eda        0
bvp        0
temp       0
x          0
y          0
z          0
emotion    0
dtype: int64

In [14]:
# checking for duplicates in df_30sn
df_30sn.duplicated().sum()

594

There are 594 duplicates.

In [15]:
# Check number of rows before
before = df_30sn.shape[0]

# Drop duplicates
df_15 = df_30sn.drop_duplicates()

# Check number of rows after
after = df_30sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 82600
Rows after: 82600
Duplicates removed: 0

In [16]:
# Check for remaining duplicates
duplicates_exist = df_30sn.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

There are still duplicates.

In [17]:
# Load the 60-second signals data
df_60sn = pd.read_csv("Data/PhysiologicalSignals/physiological_signals_60sn.csv")
df_60sn

        Subject   eda     bvp   temp   x   y   z  emotion
0             1  0.00   -0.03  31.63 -13 -18  62        0
1             1  0.04    5.06  31.63 -15 -18  62        0
2             1  0.08   17.91  31.63 -14 -17  62        0
3             1  0.08   79.34  31.63 -16 -17  60        0
4             1  0.08  228.25  31.63   3 -12  63        0
...         ...   ...     ...    ...  ..  ..  ..      ...
167995       20  0.33  -35.69  36.05 -53  23  16        1
167996       20  0.35  291.37  36.11 -66  23   1        1
167997       20  0.35  -99.97  36.11 -63  19  -8        1
167998       20  0.35  -48.63  36.11 -61  22 -10        1
167999       20  0.34   59.01  36.11 -61  20 -10        1

[168000 rows x 8 columns]

In [ ]:
# Checking the shape of the df_60sn DataFrame
df_60sn.shape

(168000, 8)

In [ ]:
# Get an overview of the df_60sn DataFrame
df_60sn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168000 entries, 0 to 167999
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Subject  168000 non-null  int64
 1   eda      168000 non-null  float64
 2   bvp      168000 non-null  float64
 3   temp     168000 non-null  float64
 4   x        168000 non-null  int64
 5   y        168000 non-null  int64
 6   z        168000 non-null  int64
 7   emotion  168000 non-null  int64
dtypes: float64(3), int64(5)
memory usage: 10.3 MB

In [18]:
# Check number of rows before
before = df_60sn.shape[0]

# Drop duplicates
df_15 = df_60sn.drop_duplicates()

# Check number of rows after
after = df_60sn.shape[0]

print(f"Rows before: {before}")
print(f"Rows after: {after}")
print(f"Duplicates removed: {before - after}")

Rows before: 168000
Rows after: 168000
Duplicates removed: 0

In [19]:
# Check for remaining duplicates
duplicates_exist = df_60sn.duplicated().any()

if duplicates_exist:
    print("There are still duplicates.")
else:
    print("All duplicates have been removed.")

There are still duplicates.

### ii.) Mergring the Physiogical Signals

In [22]:
# Fixing column name inconsistency
df_30sn.rename(columns={'subjet': 'Subject'}, inplace=True)

In [26]:
# Concatenating all three datasets
df_Merged = pd.concat([df_15sn, df_30sn, df_60sn], ignore_index=True)

In [27]:
# Verifying the merged result
print(df_Merged.shape)
print(df_Merged.head())

(289519, 9)
   Subject   eda     bvp   temp   x   y   z  emotion duration
0        1  0.00   -0.03  31.63 -13 -18  62        0      15s
1        1  0.04    5.06  31.63 -15 -18  62        0      15s
2        1  0.08   17.91  31.63 -14 -17  62        0      15s
3        1  0.08   79.34  31.63 -16 -17  60        0      15s
4        1  0.08  228.25  31.63   3 -12  63        0      15s

In [28]:
# Adding a Source Label
df_15sn['duration'] = '15s'
df_30sn['duration'] = '30s'
df_60sn['duration'] = '60s'

df_Merged = pd.concat([df_15sn, df_30sn, df_60sn], ignore_index=True)

In [30]:
# Chcking the shape of the merged DataFrame
df_Merged.shape

(289519, 9)

In [ ]:
# Dispalying the summary of the merged DataFrame
df_Merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 289519 entries, 0 to 289518
Data columns (total 9 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Subject   289519 non-null  int64
 1   eda       289519 non-null  float64
 2   bvp       289519 non-null  float64
 3   temp      289519 non-null  float64
 4   x         289519 non-null  int64
 5   y         289519 non-null  int64
 6   z         289519 non-null  int64
 7   emotion   289519 non-null  int64
 8   duration  289519 non-null  object
dtypes: float64(3), int64(5), object(1)
memory usage: 19.9+ MB

### iii.) Loading the Survey Data

In [34]:
df_Demographic = pd.read_csv('Data/Survey/demographic.csv')
df_Demographic.head()

,Subject,Gender,Age,Height(cm),Weight(kg),Industry,Occupation,MaritalStatus,SmokingStatus,Disease,Medicine
0,1,Female,62,167,95.0,public sector,Judge,single,No,Non,Non
1,2,Male,24,179,82.0,Private sector,System and Network Administrator,single,Yes,No,No
2,3,Female,54,168,110.0,public sector,Lawyer,married,No,Cardiovascular Diseases,Non
3,4,Female,22,173,57.0,Private sector,Research Assistant,single,No,Non,Citoles
4,5,Female,20,176,78.0,Private sector,Salesman,married,No,Non,Non

In [41]:
# Checking the shape of the df_Demographic DataFrame
df_Demographic.shape

(20, 11)

In [42]:
# Dispaying the summary of the df_Demographic DataFrame
df_Demographic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Subject        20 non-null     int64
 1   Gender         20 non-null     object
 2   Age            20 non-null     int64
 3   Height(cm)     20 non-null     int64
 4   Weight(kg)     20 non-null     float64
 5   Industry       20 non-null     object
 6   Occupation     20 non-null     object
 7   MaritalStatus  20 non-null     object
 8   SmokingStatus  20 non-null     object
 9   Disease        20 non-null     object
 10  Medicine       20 non-null     object
dtypes: float64(1), int64(3), object(7)
memory usage: 1.8+ KB

In [50]:
# Check for missing values in df_Demographic
df_Demographic.isnull().sum()

Subject          0
Gender           0
Age              0
Height(cm)       0
Weight(kg)       0
Industry         0
Occupation       0
MaritalStatus    0
SmokingStatus    0
Disease          0
Medicine         0
dtype: int64

There are no missing values in df_Demographic

In [37]:
df_General = pd.read_csv('Data/Survey/generalStressTest.csv')
df_General.head()

,Subject,C1,C2,C3,C4,C5,C6,C7,C8,C9,...,C12,C13,C14,C15,C16,C17,C18,C19,C20,TotalPoints
0,1,2,4,1,2,1,3,1,4,3,...,2,4,2,1,1,2,4,2,4,46
1,2,3,2,2,1,1,1,2,1,1,...,2,2,1,2,1,1,4,1,2,36
2,3,4,2,3,1,1,2,2,1,1,...,2,2,3,1,1,1,2,1,4,40
3,4,3,3,3,1,2,2,2,2,1,...,3,4,2,2,2,1,2,2,2,44
4,5,3,4,4,1,3,2,2,2,1,...,3,4,2,1,1,1,3,1,4,49

In [43]:
# Checking the Shape of the df_General DataFrame
df_General.shape

(20, 22)

In [44]:
# Displaying the summary of the df_Demographic DataFrame
df_General.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 22 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Subject      20 non-null     int64
 1   C1           20 non-null     int64
 2   C2           20 non-null     int64
 3   C3           20 non-null     int64
 4   C4           20 non-null     int64
 5   C5           20 non-null     int64
 6   C6           20 non-null     int64
 7   C7           20 non-null     int64
 8   C8           20 non-null     int64
 9   C9           20 non-null     int64
 10  C10          20 non-null     int64
 11  C11          20 non-null     int64
 12  C12          20 non-null     int64
 13  C13          20 non-null     int64
 14  C14          20 non-null     int64
 15  C15          20 non-null     int64
 16  C16          20 non-null     int64
 17  C17          20 non-null     int64
 18  C18          20 non-null     int64
 19  C19          20 non-null     int64
 20  C20          20 non-null     int64
 21  TotalPoints  20 non-null     int64
dtypes: int64(22)
memory usage: 3.6 KB

In [51]:
# Check for missing values in df_General
df_General.isnull().sum()

Subject        0
C1             0
C2             0
C3             0
C4             0
C5             0
C6             0
C7             0
C8             0
C9             0
C10            0
C11            0
C12            0
C13            0
C14            0
C15            0
C16            0
C17            0
C18            0
C19            0
C20            0
TotalPoints    0
dtype: int64

There are no missing values in df_Genral

In [40]:
df_Instant = pd.read_csv('Data/Survey/instantQuestionnaires.csv')
df_Instant.head()

   Subject           C1         C2              C3   C4            C5   C6
0        1      Neutral  Free time  Family members   No  I don't know  Yes
1        1      Tension       Work  Family members  Yes           Yes  Yes
2        1      Neutral       Work          No one   No           Yes  Yes
3        1      Pleased       Work          No one   No            No  Yes
4        1  Comfortable  Free time  Family members   No            No  Yes

In [45]:
# Checking the shape of the df_Demographic DataFrame
df_Demographic.shape

(20, 11)

In [46]:
# Dispaling the summary of the df_Demographic DataFrame
df_Instant.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  651 non-null    int64
 1   C1       651 non-null    object
 2   C2       651 non-null    object
 3   C3       650 non-null    object
 4   C4       651 non-null    object
 5   C5       651 non-null    object
 6   C6       650 non-null    object
dtypes: int64(1), object(6)
memory usage: 35.7+ KB

In [47]:
# Cheking for missing values in df_Instant
df_Instant.isnull().sum()

Subject    0
C1         0
C2         0
C3         1
C4         0
C5         0
C6         1
dtype: int64

There are a missing values in c3 and c6

In [48]:
# Filling the missing values in df_Instant with the mean of each column
df_Instant.fillna(df_Instant.mean(), inplace=True)

In [56]:
# Check if the missing values have been filled 
missing_values = df_Instant.isnull().sum()

In [65]:
df_Panas = pd.read_csv('Data/Survey/PANAS.csv')
df_Panas.head()

   Subject  C1  C2  C3  C4  C5  C6  C7  C8  C9  C10
0        1   2   3   3   1   2   2   2   2   0    1
1        2   2   3   4   2   3   0   1   3   0    2
2        3   2   1   3   2   4   1   2   1   0    1
3        4   1   3   4   3   2   3   2   2   1    3
4        5   4   3   3   4   3   2   2   1   0    0

In [68]:
# Checking the shape of the Dataframe
df_Panas.shape

(20, 11)

In [ ]:
# Displaying information about the DataFrame
df_Panas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Subject  20 non-null     int64
 1   C1       20 non-null     int64
 2   C2       20 non-null     int64
 3   C3       20 non-null     int64
 4   C4       20 non-null     int64
 5   C5       20 non-null     int64
 6   C6       20 non-null     int64
 7   C7       20 non-null     int64
 8   C8       20 non-null     int64
 9   C9       20 non-null     int64
 10  C10      20 non-null     int64
dtypes: int64(11)
memory usage: 1.8 KB

Merging the Survey Dataset

In [58]:
# Merge Demographic and General (1:1 merge)
df_merged_static = pd.merge(df_Demographic, df_General, on='Subject')

# Merge with Instant Data (1:many merge)
df_Final = pd.merge(df_Instant, df_merged_static, on='Subject', how='left')

In [59]:
df_Final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 651 entries, 0 to 650
Data columns (total 38 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Subject        651 non-null    int64
 1   C1_x           651 non-null    object
 2   C2_x           651 non-null    object
 3   C3_x           650 non-null    object
 4   C4_x           651 non-null    object
 5   C5_x           651 non-null    object
 6   C6_x           650 non-null    object
 7   Gender         651 non-null    object
 8   Age            651 non-null    int64
 9   Height(cm)     651 non-null    int64
 10  Weight(kg)     651 non-null    float64
 11  Industry       651 non-null    object
 12  Occupation     651 non-null    object
 13  MaritalStatus  651 non-null    object
 14  SmokingStatus  651 non-null    object
 15  Disease        651 non-null    object
 16  Medicine       651 non-null    object
 17  C1_y           651 non-null    int64
 18  C2_y           651 non-null    int64
 19  C3_y           651 non-null    int64
 20  C4_y           651 non-null    int64
 21  C5_y           651 non-null    int64
 22  C6_y           651 non-null    int64
 23  C7             651 non-null    int64
 24  C8             651 non-null    int64
 25  C9             651 non-null    int64
 26  C10            651 non-null    int64
 27  C11            651 non-null    int64
 28  C12            651 non-null    int64
 29  C13            651 non-null    int64
 30  C14            651 non-null    int64
 31  C15            651 non-null    int64
 32  C16            651 non-null    int64
 33  C17            651 non-null    int64
 34  C18            651 non-null    int64
 35  C19            651 non-null    int64
 36  C20            651 non-null    int64
 37  TotalPoints    651 non-null    int64
dtypes: float64(1), int64(24), object(13)
memory usage: 198.4+ KB

Loading the Facial Expression dataset

In [61]:
df_Facial = pd.read_csv('Data/TheFacialExpressions/facial_expression.csv')
df_Facial.head()

   emotion                                             pixels
0        1  105 106 105 104 103 102 101 100 98 97 95 94 94...
1        1  108 108 109 111 112 112 113 114 114 114 115 11...
2        1  109 110 111 112 113 114 115 116 116 117 118 11...
3        1  110 111 111 129 97 80 105 99 66 38 57 95 123 1...
4        1  111 115 116 115 108 77 66 63 61 62 61 62 63 63...

In [63]:
df_Facial.shape

(83, 2)

In [62]:
df_Facial.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   emotion  83 non-null     int64
 1   pixels   83 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.4+ KB

Merging All 3 Datasets